language: php

php: 
  - 7.0

before_script:
  - composer install --no-interaction

addons:
  apt:
    packages:
      - php5-fpm
      - php5-mysql
      - nginx
    
hosts:
  - localhost

before_install:
  - export PATH=vendor/bin:$PATH


before_script:
  - mysql -e "CREATE DATABASE IF NOT EXISTS hng;" -u root
  - mysql -e "CREATE USER 'hng'@'localhost' IDENTIFIED BY 'hng';" -u root
  - mysql -e "GRANT ALL PRIVILEGES ON hng.* TO 'hng'@'localhost';" -u root
  - mysql -e "FLUSH PRIVILEGES;" -u root
  - sudo service php5-fpm restart
  - sudo service nginx restart

script:
  - mysql -e "DROP DATABASE hng;" -u root
  - mysql -e "CREATE DATABASE IF NOT EXISTS hng;" -u root
  - mysql -e "GRANT ALL PRIVILEGES ON hng.* TO 'hng'@'localhost';" -u root
  - mysql -e "FLUSH PRIVILEGES;" -u root
